version: "3.8"

volumes:
  caddy_config:
  caddy_data:
  grafana_data:
  prometheus_data:

services:
  caddy:
    image: caddy:2-alpine
    container_name: minitwit_caddy
    restart: unless-stopped
    environment:
      DOMAINNAME: ${DOMAINNAME:-localhost:80}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  api:
    image: salsitu/minitwitapi:latest
    container_name: minitwit_api
    restart: unless-stopped
    volumes:
      - $HOME/db/minitwit.db:/tmp/minitwit.db
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - grafana
      - prometheus

  app:
    image: salsitu/minitwitapp:latest
    container_name: minitwit_app
    restart: unless-stopped
    volumes:
      - $HOME/db/minitwit.db:/tmp/minitwit.db
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - grafana
      - prometheus

  grafana:
    image: grafana/grafana-oss:latest
    container_name: minitwit_grafana
    restart: unless-stopped
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/home_dashboard.json"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWD:-admin}"
      GF_SERVER_DOMAIN: "${SCHEME:-http}://${DOMAINNAME:-localhost}"
      GF_SERVER_ROOT_URL: "${SCHEME:-http}://${DOMAINNAME:-localhost}/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    user: root
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:eo
      - grafana_data:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: minitwit_prometheus
    restart: unless-stopped
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus/data
    ports:
      - "127.0.0.1:9090:9090"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
