version: "3.8"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data:rw
      - ./caddy-config:/config:rw
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  minitwit-api:
    image: salsitu/minitwitapi:latest
    container_name: minitwit-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - $HOME/db:/app/minitwit_thesvindler/tmp

  minitwit-app:
    image: salsitu/minitwitapp:latest
    container_name: minitwit-app
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - $HOME/db:/app/minitwit_thesvindler/tmp

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
