version: "3.7"

services:
  caddy:
    image: caddy:2-alpine
    container_name: minitwit_caddy
    restart: unless-stopped
    environment:
      DOMAINNAME: ${DOMAINNAME:-localhost:80}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data:rw
      - ./caddy_config:/config:rw
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  api:
    image: salsitu/minitwitapi:latest
    container_name: minitwit_api
    restart: unless-stopped
    volumes:
      - $HOME/db:/app/minitwit_thesvindler/tmp
    ports:
      - "8000:8000"

  app:
    image: salsitu/minitwitapp:latest
    container_name: minitwit_app
    restart: unless-stopped
    volumes:
      - $HOME/db:/app/minitwit_thesvindler/tmp
    ports:
      - "8080:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: minitwit_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus_data
    ports:
      - "9090:9090"
    command: 
      - '--web.external-url=/prometheus/'
      - '--storage.tsdb.path=/prometheus_data'
    depends_on:
      - api
      - app

  grafana:
    image: grafana/grafana-oss:latest
    container_name: minitwit_grafana
    restart: unless-stopped
    environment:
      GF_SERVER_DOMAIN: "${SCHEME:-http}://${DOMAINNAME:-localhost}"
      GF_SERVER_ROOT_URL: "${SCHEME:-http}://${DOMAINNAME:-localhost}/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

