global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'minittwit_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000'] 
        labels:
          group: 'production'
  - job_name: 'minittwit_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080'] 
        labels:
          group: 'production'
