# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "BUILD"
      - run: cd minitwit_rewrite_go/api
      - run: docker build -t $DOCKER_USERNAME/minitwitimage:latest .
      - run: echo "PUSH"
      - run: docker push $DOCKER_USERNAME/minitwitimage:latest

  deploy:
    docker:
      - image: buildpack-deps:trusty
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - run: |
          ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
          "cd ~/docker_minitwit && \
          docker-compose pull && \
          docker-compose up -d"

workflows:
  deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
