global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'minitwit_api'
    static_configs:
      - targets: ['api:8000'] 
        labels:
          group: 'production'
  - job_name: 'minitwit_app'
    static_configs:
      - targets: ['app:8080'] 
        labels:
          group: 'production'
